<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DummyAccountsSeeder extends Seeder
{
    public function run(): void
    {
        $accounts = [
            // ── Admins ──
            [
                'name'           => 'Admin Utama',
                'email'          => 'admin.utama',
                'username'       => 'admin.utama',
                'password'       => Hash::make('Admin@2026!'),
                'role'           => 'admin',
                'dob'            => '01/01/1990',
                'status'         => 'Active',
                'gender'         => 'Male',
                'alamat'         => 'Jl. Kenanga No. 1, Bintaro',
                'phone'          => '081200000001',
            ],
            [
                'name'           => 'Admin Kedua',
                'email'          => 'admin.kedua',
                'username'       => 'admin.kedua',
                'password'       => Hash::make('Admin@2026!'),
                'role'           => 'admin',
                'dob'            => '02/02/1992',
                'status'         => 'Active',
                'gender'         => 'Female',
                'alamat'         => 'Jl. Melati No. 2, Ciputat',
                'phone'          => '081200000002',
            ],

            // ── Teachers ──
            [
                'name'           => 'Budi Hermawan',
                'email'          => 'budi.hermawan',
                'username'       => 'budi.hermawan',
                'password'       => Hash::make('Teacher@2026!'),
                'role'           => 'teacher',
                'dob'            => '15/03/1988',
                'status'         => 'Active',
                'gender'         => 'Male',
                'alamat'         => 'Jl. Anggrek No. 5, Bintaro',
                'phone'          => '081211111001',
            ],
            [
                'name'           => 'Dewi Rahayu',
                'email'          => 'dewi.rahayu',
                'username'       => 'dewi.rahayu',
                'password'       => Hash::make('Teacher@2026!'),
                'role'           => 'teacher',
                'dob'            => '22/07/1990',
                'status'         => 'Active',
                'gender'         => 'Female',
                'alamat'         => 'Jl. Mawar No. 10, Pamulang',
                'phone'          => '081211111002',
            ],
            [
                'name'           => 'Fajar Nugraha',
                'email'          => 'fajar.nugraha',
                'username'       => 'fajar.nugraha',
                'password'       => Hash::make('Teacher@2026!'),
                'role'           => 'teacher',
                'dob'            => '08/11/1985',
                'status'         => 'Active',
                'gender'         => 'Male',
                'alamat'         => 'Jl. Dahlia No. 3, Ciputat',
                'phone'          => '081211111003',
            ],
            [
                'name'           => 'Lila Kusuma',
                'email'          => 'lila.kusuma',
                'username'       => 'lila.kusuma',
                'password'       => Hash::make('Teacher@2026!'),
                'role'           => 'teacher',
                'dob'            => '14/04/1993',
                'status'         => 'Active',
                'gender'         => 'Female',
                'alamat'         => 'Jl. Flamboyan No. 8, Bintaro',
                'phone'          => '081211111004',
            ],
            [
                'name'           => 'Reza Hidayat',
                'email'          => 'reza.hidayat',
                'username'       => 'reza.hidayat',
                'password'       => Hash::make('Teacher@2026!'),
                'role'           => 'teacher',
                'dob'            => '30/09/1987',
                'status'         => 'Active',
                'gender'         => 'Male',
                'alamat'         => 'Jl. Cempaka No. 12, Pamulang',
                'phone'          => '081211111005',
            ],

            // ── Students – Kelas Beach (Funny Phonics) ──
            [
                'name'           => 'Rizky Pratama',
                'email'          => 'rizky.pratama',
                'username'       => 'rizky.pratama',
                'password'       => Hash::make('Beach2026!'),
                'role'           => 'student',
                'dob'            => '10/05/2016',
                'status'         => 'Active',
                'gender'         => 'Male',
                'alamat'         => 'Jl. Pantai Indah No. 1, Bintaro',
                'phone'          => '081222220001',
                'program_series' => 'Funny Phonics',
                'specific_level' => 'Funny Phonics 1',
                'guardian_name'  => 'Andi Pratama',
            ],
            [
                'name'           => 'Siti Aminah',
                'email'          => 'siti.aminah',
                'username'       => 'siti.aminah',
                'password'       => Hash::make('Beach2026!'),
                'role'           => 'student',
                'dob'            => '25/08/2016',
                'status'         => 'Active',
                'gender'         => 'Female',
                'alamat'         => 'Jl. Pantai Indah No. 3, Bintaro',
                'phone'          => '081222220002',
                'program_series' => 'Funny Phonics',
                'specific_level' => 'Funny Phonics 2',
                'guardian_name'  => 'Hadi Aminah',
            ],

            // ── Students – Kelas Borobudur (Hi Kids!) ──
            [
                'name'           => 'Dimas Santoso',
                'email'          => 'dimas.santoso',
                'username'       => 'dimas.santoso',
                'password'       => Hash::make('Borobudur2026!'),
                'role'           => 'student',
                'dob'            => '12/03/2015',
                'status'         => 'Active',
                'gender'         => 'Male',
                'alamat'         => 'Jl. Candi Raya No. 7, Ciputat',
                'phone'          => '081222220003',
                'program_series' => 'Hi Kids!',
                'specific_level' => 'Hi Kids! 1',
                'guardian_name'  => 'Wahyu Santoso',
            ],
            [
                'name'           => 'Naila Putri',
                'email'          => 'naila.putri',
                'username'       => 'naila.putri',
                'password'       => Hash::make('Borobudur2026!'),
                'role'           => 'student',
                'dob'            => '05/11/2015',
                'status'         => 'Active',
                'gender'         => 'Female',
                'alamat'         => 'Jl. Candi Raya No. 9, Ciputat',
                'phone'          => '081222220004',
                'program_series' => 'Hi Kids!',
                'specific_level' => 'Hi Kids! 2',
                'guardian_name'  => 'Agus Putri',
            ],

            // ── Students – Kelas Forest (Oxford Phonics) ──
            [
                'name'           => 'Alif Mahendra',
                'email'          => 'alif.mahendra',
                'username'       => 'alif.mahendra',
                'password'       => Hash::make('Forest2026!'),
                'role'           => 'student',
                'dob'            => '18/01/2014',
                'status'         => 'Active',
                'gender'         => 'Male',
                'alamat'         => 'Jl. Hutan Raya No. 4, Pamulang',
                'phone'          => '081222220005',
                'program_series' => 'Oxford Phonics',
                'specific_level' => 'Oxford Phonics 1',
                'guardian_name'  => 'Brama Mahendra',
            ],
            [
                'name'           => 'Zahra Amelia',
                'email'          => 'zahra.amelia',
                'username'       => 'zahra.amelia',
                'password'       => Hash::make('Forest2026!'),
                'role'           => 'student',
                'dob'            => '30/06/2014',
                'status'         => 'Active',
                'gender'         => 'Female',
                'alamat'         => 'Jl. Hutan Raya No. 6, Pamulang',
                'phone'          => '081222220006',
                'program_series' => 'Oxford Phonics',
                'specific_level' => 'Oxford Phonics 2',
                'guardian_name'  => 'Firman Amelia',
            ],

            // ── Students – Kelas Liberty (Abracadabra) ──
            [
                'name'           => 'Bagas Wicaksono',
                'email'          => 'bagas.wicaksono',
                'username'       => 'bagas.wicaksono',
                'password'       => Hash::make('Liberty2026!'),
                'role'           => 'student',
                'dob'            => '22/04/2013',
                'status'         => 'Active',
                'gender'         => 'Male',
                'alamat'         => 'Jl. Kemerdekaan No. 2, Bintaro',
                'phone'          => '081222220007',
                'program_series' => 'Abracadabra',
                'specific_level' => 'Abracadabra 1',
                'guardian_name'  => 'Irfan Wicaksono',
            ],
            [
                'name'           => 'Meika Salsabila',
                'email'          => 'meika.salsabila',
                'username'       => 'meika.salsabila',
                'password'       => Hash::make('Liberty2026!'),
                'role'           => 'student',
                'dob'            => '09/09/2013',
                'status'         => 'Active',
                'gender'         => 'Female',
                'alamat'         => 'Jl. Kemerdekaan No. 5, Bintaro',
                'phone'          => '081222220008',
                'program_series' => 'Abracadabra',
                'specific_level' => 'Abracadabra 2',
                'guardian_name'  => 'Toni Salsabila',
            ],

            // ── Students – Kelas Machu Picchu (Get Smart) ──
            [
                'name'           => 'Farel Aditya',
                'email'          => 'farel.aditya',
                'username'       => 'farel.aditya',
                'password'       => Hash::make('MachuPicchu2026!'),
                'role'           => 'student',
                'dob'            => '14/07/2012',
                'status'         => 'Active',
                'gender'         => 'Male',
                'alamat'         => 'Jl. Pegunungan No. 11, Ciputat',
                'phone'          => '081222220009',
                'program_series' => 'Get Smart',
                'specific_level' => 'Get Smart 1',
                'guardian_name'  => 'Dedi Aditya',
            ],
            [
                'name'           => 'Kezia Natasya',
                'email'          => 'kezia.natasya',
                'username'       => 'kezia.natasya',
                'password'       => Hash::make('MachuPicchu2026!'),
                'role'           => 'student',
                'dob'            => '28/02/2012',
                'status'         => 'Active',
                'gender'         => 'Female',
                'alamat'         => 'Jl. Pegunungan No. 13, Ciputat',
                'phone'          => '081222220010',
                'program_series' => 'Get Smart',
                'specific_level' => 'Get Smart 2',
                'guardian_name'  => 'Rudi Natasya',
            ],

            // ── Students – Kelas Mars (Full Blast) ──
            [
                'name'           => 'Hafidz Ramadan',
                'email'          => 'hafidz.ramadan',
                'username'       => 'hafidz.ramadan',
                'password'       => Hash::make('Mars2026!'),
                'role'           => 'student',
                'dob'            => '03/10/2011',
                'status'         => 'Active',
                'gender'         => 'Male',
                'alamat'         => 'Jl. Planet Merah No. 6, Pamulang',
                'phone'          => '081222220011',
                'program_series' => 'Full Blast',
                'specific_level' => 'Full Blast 1',
                'guardian_name'  => 'Yusuf Ramadan',
            ],
            [
                'name'           => 'Putri Andini',
                'email'          => 'putri.andini',
                'username'       => 'putri.andini',
                'password'       => Hash::make('Mars2026!'),
                'role'           => 'student',
                'dob'            => '16/05/2011',
                'status'         => 'Active',
                'gender'         => 'Female',
                'alamat'         => 'Jl. Planet Merah No. 8, Pamulang',
                'phone'          => '081222220012',
                'program_series' => 'Full Blast',
                'specific_level' => 'Full Blast 2',
                'guardian_name'  => 'Hendra Andini',
            ],

            // ── Students – Kelas Mountain (Test Preparation) ──
            [
                'name'           => 'Arya Pratama',
                'email'          => 'arya.pratama',
                'username'       => 'arya.pratama',
                'password'       => Hash::make('Mountain2026!'),
                'role'           => 'student',
                'dob'            => '19/12/2007',
                'status'         => 'Active',
                'gender'         => 'Male',
                'alamat'         => 'Jl. Gunung Tinggi No. 3, Bintaro',
                'phone'          => '081222220013',
                'program_series' => 'Test Preparation',
                'specific_level' => 'TOEFL',
                'guardian_name'  => 'Bambang Pratama',
            ],
            [
                'name'           => 'Bunga Lestari',
                'email'          => 'bunga.lestari',
                'username'       => 'bunga.lestari',
                'password'       => Hash::make('Mountain2026!'),
                'role'           => 'student',
                'dob'            => '07/08/2007',
                'status'         => 'Active',
                'gender'         => 'Female',
                'alamat'         => 'Jl. Gunung Tinggi No. 5, Bintaro',
                'phone'          => '081222220014',
                'program_series' => 'Test Preparation',
                'specific_level' => 'IELTS',
                'guardian_name'  => 'Sugeng Lestari',
            ],

            // ── Students – Kelas Online Zoom (Conversation Class) ──
            [
                'name'           => 'Galih Permana',
                'email'          => 'galih.permana',
                'username'       => 'galih.permana',
                'password'       => Hash::make('OnlineZoom2026!'),
                'role'           => 'student',
                'dob'            => '23/03/2009',
                'status'         => 'Active',
                'gender'         => 'Male',
                'alamat'         => 'Jl. Digital No. 1, Ciputat',
                'phone'          => '081222220015',
                'program_series' => 'Conversation Class',
                'guardian_name'  => 'Eko Permana',
            ],
            [
                'name'           => 'Hana Safitri',
                'email'          => 'hana.safitri',
                'username'       => 'hana.safitri',
                'password'       => Hash::make('OnlineZoom2026!'),
                'role'           => 'student',
                'dob'            => '11/06/2009',
                'status'         => 'Active',
                'gender'         => 'Female',
                'alamat'         => 'Jl. Digital No. 3, Ciputat',
                'phone'          => '081222220016',
                'program_series' => 'Conversation Class',
                'guardian_name'  => 'Imam Safitri',
            ],

            // ── Students – Kelas Saturn (Private Class) ──
            [
                'name'           => 'Ivan Kurniawan',
                'email'          => 'ivan.kurniawan',
                'username'       => 'ivan.kurniawan',
                'password'       => Hash::make('Saturn2026!'),
                'role'           => 'student',
                'dob'            => '05/01/2010',
                'status'         => 'Active',
                'gender'         => 'Male',
                'alamat'         => 'Jl. Saturnus No. 9, Pamulang',
                'phone'          => '081222220017',
                'program_series' => 'Private Class',
                'specific_level' => 'Private Class Offline',
                'guardian_name'  => 'Joko Kurniawan',
            ],
            [
                'name'           => 'Jesica Cantika',
                'email'          => 'jesica.cantika',
                'username'       => 'jesica.cantika',
                'password'       => Hash::make('Saturn2026!'),
                'role'           => 'student',
                'dob'            => '20/09/2010',
                'status'         => 'Active',
                'gender'         => 'Female',
                'alamat'         => 'Jl. Saturnus No. 11, Pamulang',
                'phone'          => '081222220018',
                'program_series' => 'Private Class',
                'specific_level' => 'Private Class Online',
                'guardian_name'  => 'Krisna Cantika',
            ],
        ];

        foreach ($accounts as $data) {
            User::updateOrCreate(
                ['email' => $data['email']],
                $data
            );
        }

        $this->command->info('✅ ' . count($accounts) . ' dummy accounts seeded successfully!');
    }
}
